### PR TITLE
Add scale test in dormant (-short) mode

### PR DESCRIPTION
**Pull request by jnpacker**
Signed-off-by: Joshua Packer <jpacker@redhat.com>

* Include the scale-cluster-curator-controller_test.go for manual scale testing and pod profiling

### CODE REVIEW

**Comment by leena-jawale** [comment]
Looks good. Can this be run in unit-tests job?

**Comment by jnpacker** [comment]
No. It needs to be run on a full cluster, so its something we could add to end-2-end. You just need to run the make command if your connected to a cluster.  I wanted a profile/scale test that could be run on a real system.

**Pull request merged**
